name: Trigger auto deployment for sample-agent-pool-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/sample-agent-pool-ca-AutoDeployTrigger-d2cb8696-ef4c-4f0c-be35-267c73ceb44b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acrccspoc.azurecr.io
          username: ${{ secrets.SAMPLEAGENTPOOLCA_REGISTRY_USERNAME }}
          password: ${{ secrets.SAMPLEAGENTPOOLCA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrccspoc.azurecr.io/ageentpool:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SAMPLEAGENTPOOLCA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n sample-agent-pool-ca -g rg-ccs-poc-eastus --server acrccspoc.azurecr.io --username  ${{ secrets.SAMPLEAGENTPOOLCA_REGISTRY_USERNAME }} --password ${{ secrets.SAMPLEAGENTPOOLCA_REGISTRY_PASSWORD }}
            az containerapp update -n sample-agent-pool-ca -g rg-ccs-poc-eastus --image acrccspoc.azurecr.io/ageentpool:${{ github.sha }}
